[package]
name = "flare-core-tauri-app"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
flare-im-core-sdk-tauri = { path = "../../../../flare-im-core-sdk/bindings/tauri", features = ["quic"] }
tauri = { version = "2.11", features = ["macos-private-api", "protocol-asset"] }
tauri-plugin-dialog = "2.7.1"
tauri-plugin-notification = "2.3.3"
tauri-plugin-opener = "2.5.4"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }
